services:
  nginx_proxy:
    extends:
      service: nginx_proxy_base
      file: docker-compose.services.yml
    networks:
      - proxy_network

  redis:
    extends:
      service: redis_base
      file: docker-compose.services.yml
    volumes:
      - redis_data:/data
    networks:
      - proxy_network

volumes:
  redis_data:

networks:
  proxy_network:
    driver: bridge
